[package]
name = "bitcoin_wallet_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
wasm-bindgen-futures = "0.4.42"
yew = "0.21.0"
